### ISSUE TITLE
How to setup with Neovim?

### ISSUE THREAD

**Issue by adonespitogo** [lasorda/protobuf-language-server#11]

**Comment by lasorda** [comment]
I use neovim with [coc.nvim](https://github.com/neoclide/coc.nvim)，this is my [neovim config ](https://github.com/lasorda/vimrc)，you can check the `coc-settings.json`
```json 
{
    "languageserver": {
        "proto": {
            "command": "pls",
            "filetypes": [
                "proto",
                "cpp"
            ]
        },
        "bash": {
            "command": "bash-language-server",
            "args": [
                "start"
            ],
            "filetypes": [
                "sh"
            ]
        }
    }
}
```

**Comment by adonespitogo** [comment]
Sorry, I should've been more specific. I'm using` nvim-lspconfig`. What's the equivalent setup for lspconfig?

**Comment by BrotifyPacha** [comment]
@adonespitogo Hi, readme now has instructions for `lsp-config.nvim` users
