### ISSUE TITLE
Visual Studio Code plugin does not work

### ISSUE THREAD

**Issue by wrmbaron** [lasorda/protobuf-language-server#20]
The Visual Studio Code plugin does not work. Here is the error output of the language server:

```
flag provided but not defined: -stdio
Usage of protobuf-language-server:
  -listen string
    	address on which to listen for remote connections
  -logs string
    	logs file path (default "C:\\Users\\itsame/.protobuf-language-server.log")
[Error - 4:28:46 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:28:46 PM] Connection to server got closed. Server will restart.
true
[Error - 4:28:46 PM] protobuf-language-server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

Apparently the server gets started with incompatible arguments.

I downloaded and installed everything fresh from Github (274197af43657986e7c950fef90cfb190ea5a5e7) after the downloadable plugin from the registry did not work, but the effect is the same.

**Comment by lasorda** [comment]
https://github.com/lasorda/protobuf-language-server/pull/21 this commit fix vscode

**Comment by lasorda** [comment]
@BrotifyPacha check this

**Comment by BrotifyPacha** [comment]
Yeah, your fix should do it. 

Apparently vscode sends `-stdio` argument to language servers. It wasn’t an issue previously because `main()` wasn’t calling `flag.Parse()` before i refactored it.
