### ISSUE TITLE
suggestion: add to mason-registry

### ISSUE THREAD

**Issue by 3DRX** [lasorda/protobuf-language-server#23]
https://github.com/mason-org/mason-registry/blob/main/CONTRIBUTING.md

mason is the goto tool to manage language servers in neovim, should we consider making this available in mason too? I'm willing to help.

**Comment by lasorda** [comment]
ok

**Comment by 3DRX** [comment]
I've been working on the package.yaml required for mason, it'd be nice to have a release tag rather than `protobuf-language-server@v0.0.0-xxxxx-xxxx`.

**Comment by 3DRX** [comment]
> I've been working on the package.yaml required for mason, it'd be nice to have a release tag rather than `protobuf-language-server@v0.0.0-xxxxx-xxxx`.

https://github.com/mason-org/mason-registry/pull/7853

**Comment by lasorda** [comment]
> I've been working on the package.yaml required for mason, it'd be nice to have a release tag rather than `protobuf-language-server@v0.0.0-xxxxx-xxxx`.

I create release v0.1.0 https://github.com/lasorda/protobuf-language-server/tree/v0.1.0
