### ISSUE TITLE
是否支持与 AstroNvim 整合？

### ISSUE THREAD

**Issue by lonnywong** [lasorda/protobuf-language-server#9]
我用的是 [AstroNvim](https://github.com/AstroNvim/AstroNvim) ，`~/.config/nvim/lua/user/init.lua` 配置如下：
```lua
return {
  lsp = {
    servers = {
      "pls",
    },
    config = {
      clangd = {
        filetypes = { "c", "cpp", "objc", "objcpp", "cuda" },
      },
      pls = function()
        return {
          cmd = { "pls" },
          filetypes = "proto",
          root_dir = require("lspconfig.util").root_pattern ".git",
        }
      end,
    },
  },
}
```

配置文档可以参考：https://docs.astronvim.com/recipes/advanced_lsp/#lsp-setup-without-installer

用 `nvim` 打开 `proto` 文件后，发现 `pls` 在运行中了，但是补全和错误提示等功能都没有。

在 `~/.pls.log` 中有 `parseProto err <input>:8:17: found "//" but expected [field identifier]`，但是在 `nvim` 中没有显示。

**Comment by lasorda** [comment]
这种估计是语法错误，语法解析失败了，可以用https://github.com/emicklei/proto 验证下

**Comment by lonnywong** [comment]
是故意写了行错误的，希望可以显示诊断信息，例如：

![image](https://github.com/lasorda/protobuf-language-server/assets/20320324/dff79a69-7a8d-47b7-93e0-3606a23d5e16)

**Comment by lasorda** [comment]
补全有少部分的功能，错误提示还没加

**Comment by lonnywong** [comment]
哪些可以补全？格式化是生效的。

**Comment by lasorda** [comment]
当前文件的message可以补全
![image](https://github.com/lasorda/protobuf-language-server/assets/7352092/e28ea4f7-93ee-4f4b-89fd-61dc4061949c)

**Comment by lonnywong** [comment]
proto 的关键字是不是也可以做到补全？如：
- message
- optional
- string
- uint32

**Comment by lasorda** [comment]
> proto 的关键字是不是也可以做到补全？如：
> 
> * message
> * optional
> * string
> * uint32

添加了诊断信息功能，将解析的错误解析行号，展示到对应的位置，https://github.com/lasorda/protobuf-language-server/commit/df4c38c4525695826aebb6e4c1bb50f2e1e4fccc

关键字提示的功能，建议通过snippets来做

**Comment by lonnywong** [comment]
谢谢大佬！好像很多 lsp 都支持补全关键字？

**Comment by lasorda** [comment]
> 谢谢大佬！好像很多 lsp 都支持补全关键字？

不想搞了，你想搞的话，可以参考代码在completion.go里面搞下提个merge

**Comment by lonnywong** [comment]
> 不想搞了，你想搞的话，可以参考代码在completion.go里面搞下提个merge

感谢大佬。我没研究过 lsp 怎么写，我抽空去学学。
